# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_login', models.CharField(max_length=200)),
                ('article_pass', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
